[tool.black]
line-length = 120
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120

[tool.flake8]
ignore = ['E203', 'E266', 'E501', 'W503', 'F403', 'F405', 'C901']
per-file-ignores = [
    '__init__.py:F401',
]
max-line-length = 120
max-complexity = 18

[tool.mypy]
strict = true
warn_return_any = false
ignore_missing_imports = true
implicit_reexport = true
